---
title: "Additional graphics"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Additional graphics}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
    collapse = TRUE,
    comment = "#>"
)
```

```{r setup, echo = FALSE, warning = FALSE}
library(GimmeMyPlot)
library(RColorBrewer)
library(magrittr)
library(ggalluvial)
set.seed(0)
```

## Venn diagrams
```{r venn}
x <- lapply(
    seq(3),
    function(x) {
        runif(10, 1, 10) %>%
            round() %>%
            letters[.] %>%
            unique() %>%
            paste("Element", .)
    }
) %>%
    set_names(paste("Dataset", LETTERS[seq(3)]))

# Default parameters
plot_venn(x)
```

```{r venn_adv, fig.width = 5}
# Advanced parameters
plot_venn(
    x,
    width_label = 5,
    colour = brewer.pal(3, "Reds"),
    color_gradient = c("white", "red"),
    cex = 1.2,
    cex_main = 1.2 * 6,
    n_max = 2,
    vjust_label = 0.75,
    ratio = 0.2
)

plot_venn(
    x,
    width_text = 8,
    width_label = 5,
    colour = brewer.pal(3, "Reds"),
    cex = 1.2,
    cex_main = 1.2 * 6,
    n_max = 2,
    vjust_label = 0.75,
    ratio = 0.5,
    label = FALSE,
    element = FALSE,
    percent = FALSE
)
```

## Radar charts
```{r radar, fig.width = 6, fig.height = 5}
df <- sapply(
    seq(2),
    function(x) {
        runif(10, 1, 100) %>%
            set_names(paste("Variable", letters[seq(10)]))
    }
) %>% set_colnames(paste("Sample", LETTERS[seq(2)]))

# Default parameters
plot_radar(df[, 1])
```

```{r radar_adv, fig.width = 7, fig.height = 5}
# Advanced parameters
plot_radar(
    df,
    colour = c("orange", "forestgreen"),
    cex = 0.9,
    n_max = 100,
    digits = 1,
    n_interval = 4,
    alpha = 0.5
)
```

## Alluvial diagrams
```{r alluvial, fig.width = 5}
x <- lapply(seq(3), function(x) {
    runif(100, 1, 3) %>%
        round() %>%
        letters[.]
}) %>%
    as.data.frame() %>%
    set_colnames(paste("variable", LETTERS[seq(3)]))
x[x == "a"] <- NA
x[, 3][is.na(x[, 3])] <- "a"

# Default parameters
plot_alluvial(x)

# Advanced parameters
plot_alluvial(
    x,
    width_label = 5,
    colour = rev(brewer.pal(3, "Reds")),
    cex = 1.2
)
```

## Multiple correlation
### Heatmaps
```{r mcor, fig.width = 6, fig.height = 5}
x <- runif(20)
x <- lapply(
    c(1, -1),
    function(i) sapply(seq(10), function(j) x * i + runif(10, max = 1))
) %>%
    Reduce(cbind, .) %>%
    set_colnames(paste("Variable", seq(20)))

# Default parameters
plot_mcor(x)

# Advanced parameters
plot_mcor(
    x,
    colour = c("black", brewer.pal(n = 6, name = "RdBu"), 1),
    method = "spearman",
    method_adjust = "none",
    cex = 0.8
)
```

### Networks
```{r cor_net, fig.width = 6, fig.height = 5}
# plot_cor_network(x)
# plot_cor_network(
#     x,
#     colour_edge = c(brewer.pal(3, "Pastel1")[3], brewer.pal(3, "Pastel1")[1]),
#     colour_node = c("white", "black"),
#     cex = 1.5,
#     method = "pearson",
#     method_adjust = "none",
#     cutoff = 0.7,
#     digits = 1
# )
```

## Networks
### Classic
```{r network, fig.width = 5, fig.height = 5}
# Default parameters
m <- correlate(x) %>%
    .[[1]] %>%
    head(10) %>%
    .[, seq(10)]
plot_network(m)
```

```{r network_adv, fig.width = 7, fig.height = 7}
# Advanced parameters
e <- Edge(m)
n <- Node(e)
plot_network(
    cex = 1.5,
    color = c("white", "gray30"),
    shape = "none",
    dashed = FALSE,
    edge = e,
    node = n,
    dist = 0,
    label = TRUE
)
```

### Dynamic
```{r net_dyn, fig.width = 6, fig.height = 5}
# Default parameters
plot_network_dyn(m)

# Advanced parameters
plot_network_dyn(
    cex = 1.5,
    color = c("white", "gray"),
    shape = "square",
    dashed = FALSE,
    edge = e,
    node = n
)
```

# Session information
```{r end, echo = FALSE}
sessionInfo()
```
