---
title: "Visualize data distribution"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Visualize data distribution}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
    collapse = TRUE,
    comment = "#>"
)
```

```{r setup, echo = FALSE, warning = FALSE}
library(GimmeMyPlot)
library(RColorBrewer)
library(magrittr)
set.seed(0)
```

## Numerical data
### Violin plots
```{r violin}
# Default parameters
x <- runif(10)
plot_violin(x)
```

```{r violin_adv, fig.width = 5, fig.height = 5}
# Multiple variables
df <- lapply(seq(2), function(x) runif(10))
df <- as.data.frame(df)
df[, 3] <- runif(10, 1, 2)
colnames(df) <- paste0("X", seq(3))
plot_violin(
    df,
    title = "Some numerical variables",
    colour = brewer.pal(9, "Set1")[seq(3)]
)

# Advanced parameters
plot_violin(
    df,
    title = "Some numerical variables",
    color_title = brewer.pal(9, "Set1")[5],
    ylab = "Y-values",
    colour = brewer.pal(9, "Set1")[seq(3)],
    method = "kruskal",
    method_adjust = "none",
    cex = 1.2,
    pch_size = 3,
    width_text = 5,
    pch_colour = "gray30",
    pch_alpha = 0.5,
    width_title = 30,
    lwd = 1.25,
    digits = 2
)
```

### Histograms
```{r hist, fig.width = 3.5}
# Default parameters
x <- rnorm(100)
plot_histogram(x)

# Advanced parameters
plot_histogram(
    x,
    title = "Some numerical variable",
    width_title = 15,
    color = "blue",
    color_title = "orange",
    color_stats = "orange",
    cex = 1.2,
    digits = 1,
    binwidth = 0.5
)
```

### Barplots
```{r barplot}
# Default parameters
x <- runif(10, 1, 10) %>%
    set_names(paste("Sample", LETTERS[seq(10)]))
plot_bar(x)
```

```{r barplot_adv, fig.width = 7}
# Advanced parameters
plot_bar(
    x = x,
    title = "Some numerical variable",
    width_title = 30,
    colour = c("yellow", "gray", "red"),
    color_title = "blue",
    cex = 1.2,
    digits = 1,
    n_max = 5,
    ratio = 15,
    hjust_title = 1
)
```

## Categorical data
### Piecharts for a single variable
```{r pie, fig.width = 5}
# Default parameters
x <- c(rep("A", 5), rep("B", 4))
plot_pie(x)
```

```{r pie_adv, fig.width = 7, fig.height = 5}
# Advanced parameters
plot_pie(
    x,
    label = TRUE,
    legend = FALSE,
    sort = FALSE,
    percent = FALSE
)
plot_pie(
    x,
    sort = c("A", "B"),
    legend = paste("Level", seq(2)),
    sample_size = 11,
    threshold = 20
)

k <- 10
n <- runif(k, 1, 10) %>% round()
x <- paste("Level", seq(k)) %>%
    mapply(function(x, y) rep(x, y), ., n) %>%
    unlist()
plot_pie(
    x,
    title = "Some categorical variable",
    width_text = 20,
    width_title = 20,
    colour = rev(brewer.pal(9, "Reds")),
    cex = 20,
    digits = 1,
    hsize = 1.5,
    collapse = TRUE,
    b = 3
)
```

### Barplots for multiple variables (or for a variable whose levels may be present simultaneously)
```{r bar_mcat, fig.width = 6, fig.height = 5}
# Default parameters
df <- sapply(seq(10), function(x) runif(10) %>% round()) %>% as.data.frame()
colnames(df) <- paste("Level", seq(10))
plot_bar_mcat(df)
```

```{r bar_mcat_adv, fig.width = 7, fig.height = 5}
# Advanced parameters
plot_bar_mcat(
    df,
    sample_size = 15,
    title = "Some categorical variable",
    width_text = 30,
    width_title = 50,
    colour_gradient = brewer.pal(9, "Reds"),
    color_title = "red",
    cex = 8,
    digits = 1,
    collapse = TRUE,
    ratio = 2,
    n_collapse = 3,
    n_max = 4,
    hjust_title = 1
)
```

# Session information
```{r end, echo = FALSE}
sessionInfo()
```
