utils::globalVariables(
    c(
        ".",
        "...",
        "f",
        "is",
        "label",
        "mat",
        "name",
        "p.adj.signif",
        "p_mat",
        "pos",
        "size",
        "text",
        "val",
        "value",
        "y_lab",
        "y.position"
    )
)
